
project_id = "wcitdamvochthvxvtxyb"

# This flag tells if you're running in local development or production
# We suggest keeping `debug = true` for development
debug = true

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
port = 54327

[auth]
port = 54328

[vector]
port = 54329

# For functions deployed locally through the CLI
[functions]
debug = true

[functions.challonge]
verify_jwt = true
