import type { PostgrestError } from '@supabase/supabase-js';

import { supabase } from '@/integrations/supabase/client';
import { handleDatabaseError } from '@/utils/errorHandler';

/**
 * A message sent from the /contact page. Written only by the
 * `send-support-email` edge function using the service role; admins may read
 * and update, but there is deliberately no DELETE policy, so this service has
 * no remove().
 */
export interface SupportTicketRow {
  id: string;
  name: string;
  email: string;
  subject: string;
  message: string;
  status: 'new' | 'resolved';
  created_at: string;
}

// TODO(types): temporary cast, same precedent as PowerWeightSandboxService. The
// support_tickets table is created by migration 20260722130000, and
// src/integrations/supabase/types.ts is regenerated by Lovable only after that
// migration reaches the live project. Until then the generated Database type
// doesn't know the table, so reads go through this narrow untyped binding.
// Remove it (and use supabase.from directly with Tables<'support_tickets'>)
// once types.ts includes support_tickets.
type UntypedFrom = (table: string) => {
  select: {
    (columns: string): {
      order: (
        column: string,
        opts: { ascending: boolean }
      ) => {
        limit: (n: number) => PromiseLike<{ data: unknown; error: PostgrestError | null }>;
      };
    };
    (
      columns: string,
      opts: { count: 'exact'; head: true }
    ): {
      eq: (
        column: string,
        value: string
      ) => PromiseLike<{ count: number | null; error: PostgrestError | null }>;
    };
  };
  update: (values: Record<string, unknown>) => {
    eq: (column: string, value: string) => PromiseLike<{ error: PostgrestError | null }>;
  };
};
const untypedFrom = supabase.from.bind(supabase) as unknown as UntypedFrom;

// "Not applied yet" error codes, same set PowerWeightSandboxService keys on:
// PGRST205: PostgREST schema-cache miss for a table
// 42P01:    undefined relation
const NOT_APPLIED_CODES = ['PGRST205', '42P01'];

const COLUMNS = 'id, name, email, subject, message, status, created_at';

export const SupportTicketService = {
  /**
   * Every support ticket, newest first. A missing table means the migration
   * hasn't been applied to this project yet — reported as an empty list rather
   * than thrown, so the admin inbox still renders its other source.
   */
  fetchAll: async (limit = 100): Promise<SupportTicketRow[]> => {
    const { data, error } = await untypedFrom('support_tickets')
      .select(COLUMNS)
      .order('created_at', { ascending: false })
      .limit(limit);

    if (error) {
      if (NOT_APPLIED_CODES.includes(error.code)) return [];
      handleDatabaseError(error, 'Failed to fetch support tickets');
    }
    return (data ?? []) as SupportTicketRow[];
  },

  /**
   * How many tickets are still unresolved. Used by the ops-health tile that
   * links to the Contact Inbox, which lists tickets alongside contact
   * requests. Returns 0, not an error, when the migration is not applied.
   */
  countNew: async (): Promise<number> => {
    const { count, error } = await untypedFrom('support_tickets')
      .select('id', { count: 'exact', head: true })
      .eq('status', 'new');

    if (error) {
      if (NOT_APPLIED_CODES.includes(error.code)) return 0;
      handleDatabaseError(error, 'Failed to count new support tickets');
    }
    return count ?? 0;
  },

  markResolved: async (id: string): Promise<void> => {
    const { error } = await untypedFrom('support_tickets')
      .update({ status: 'resolved' })
      .eq('id', id);
    if (error) handleDatabaseError(error, 'Failed to mark support ticket resolved');
  },

  reopen: async (id: string): Promise<void> => {
    const { error } = await untypedFrom('support_tickets').update({ status: 'new' }).eq('id', id);
    if (error) handleDatabaseError(error, 'Failed to reopen support ticket');
  },
};
