
import { PlayoffGame } from "@/types/playoffs";

export interface ParsedScore {
  team1Score: number;
  team2Score: number;
  games: PlayoffGame[];
}

/**
 * Utility for parsing and validating score strings
 */
export class ScoreParser {
  /**
   * Parse a score string like "2-1" into individual scores
   * @param scoreText Score text like "2-1"
   * @param matchId Match ID for game records
   * @returns Parsed score data
   */
  static parseScoreString(scoreText: string, matchId: string): ParsedScore {
    const scores = scoreText.split('-').map(s => parseInt(s.trim()));
    
    if (scores.length !== 2 || isNaN(scores[0]) || isNaN(scores[1])) {
      throw new Error('Invalid score format. Please use format like "2-1"');
    }
    
    const team1Score = scores[0];
    const team2Score = scores[1];
    
    // Validate the scores
    if (team1Score < 0 || team2Score < 0) {
      throw new Error('Scores cannot be negative');
    }
    
    // For a best-of-3 match:
    if (team1Score > 2 && team2Score > 2) {
      throw new Error('Invalid scores for a best-of-3 match');
    }
    
    // Create placeholder games based on the score
    const games: PlayoffGame[] = [];
    
    // Team 1 wins
    for (let i = 0; i < team1Score; i++) {
      games.push({
        id: '',  // Will be generated by database
        matchId: matchId,
        gameNumber: i + 1,
        team1Score: 21,  // Placeholder scores
        team2Score: 15,
        winnerId: null    // Will be filled by caller
      });
    }
    
    // Team 2 wins
    for (let i = 0; i < team2Score; i++) {
      games.push({
        id: '',  // Will be generated by database
        matchId: matchId,
        gameNumber: team1Score + i + 1,
        team1Score: 15,  // Placeholder scores
        team2Score: 21,
        winnerId: null    // Will be filled by caller
      });
    }
    
    return { team1Score, team2Score, games };
  }
  
  /**
   * Validate that scores make sense for a best-of-N match
   * @param team1Score Team 1's score
   * @param team2Score Team 2's score
   * @param bestOf The best-of number (3, 5, 7, etc)
   * @returns True if valid
   */
  static validateMatchScore(team1Score: number, team2Score: number, bestOf: number): boolean {
    // Scores must be non-negative
    if (team1Score < 0 || team2Score < 0) {
      return false;
    }
    
    const neededToWin = Math.ceil(bestOf / 2);
    const totalGames = team1Score + team2Score;
    
    // Check that someone has won enough games
    if (team1Score < neededToWin && team2Score < neededToWin) {
      return false;
    }
    
    // Check that winner doesn't have too many games
    if (team1Score > neededToWin && team2Score > 0) {
      return false;
    }
    
    if (team2Score > neededToWin && team1Score > 0) {
      return false;
    }
    
    // Check that total games doesn't exceed bestOf
    if (totalGames > bestOf) {
      return false;
    }
    
    return true;
  }
  
  /**
   * Get winner ID based on scores
   * @param team1Score Team 1's score
   * @param team2Score Team 2's score
   * @param team1Id Team 1's ID
   * @param team2Id Team 2's ID
   * @returns Winner's ID or null if tie
   */
  static getWinnerId(
    team1Score: number, 
    team2Score: number, 
    team1Id: string | null, 
    team2Id: string | null
  ): string | null {
    if (team1Score > team2Score) {
      return team1Id;
    } else if (team2Score > team1Score) {
      return team2Id;
    }
    return null;
  }
  
  /**
   * Get loser ID based on scores
   * @param team1Score Team 1's score
   * @param team2Score Team 2's score
   * @param team1Id Team 1's ID
   * @param team2Id Team 2's ID
   * @returns Loser's ID or null if tie
   */
  static getLoserId(
    team1Score: number, 
    team2Score: number, 
    team1Id: string | null, 
    team2Id: string | null
  ): string | null {
    if (team1Score < team2Score) {
      return team1Id;
    } else if (team2Score < team1Score) {
      return team2Id;
    }
    return null;
  }
}
