import { useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';

import { createDateWithTime } from '@/components/schedule/form-utils';
import { useToast } from '@/hooks/useToast';
import {
  fetchActiveSeasonIdOptional,
  saveAutoScheduleMatches,
} from '@/services/matches/MatchWriteService';
import { AutoScheduleMatch } from '@/types/autoSchedule';
import { validateMatchSchedule } from '@/utils/autoSchedule/validation';
import { errorLog, scheduleLog } from '@/utils/logger';

import { clearAutoScheduleState } from './storage';

export function useAutoScheduleSave() {
  const [isSaving, setIsSaving] = useState(false);
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const saveMatches = async (
    matches: AutoScheduleMatch[],
    selectedDate: Date | null,
    dualMatchMode: boolean = false,
    seasonId?: string | null
  ): Promise<boolean> => {
    if (!selectedDate || !matches || matches.length === 0) {
      toast({
        title: 'Error',
        description: 'No matches to save or date not selected',
        variant: 'destructive',
      });
      return false;
    }

    setIsSaving(true);

    try {
      // Use provided seasonId to avoid redundant fetch
      let activeSeasonId = seasonId;

      // Fallback: fetch active season if not provided (backwards compatibility)
      if (!activeSeasonId) {
        activeSeasonId = await fetchActiveSeasonIdOptional();
      }

      // Validate matches using central validation utility
      const validation = await validateMatchSchedule(matches);
      if (!validation.isValid) {
        const errorMessages = validation.errors.map(e => e.message).join('; ');
        throw new Error(`Schedule validation failed: ${errorMessages}`);
      }

      // Build per-timeslot court counters
      const timeslotCourtCounters = new Map<string, number>();
      const matchesToInsert = matches.map((match) => {
        const dateWithTime = createDateWithTime(selectedDate, match.timeslot);
        const courtNum = (timeslotCourtCounters.get(match.timeslot) || 0) + 1;
        timeslotCourtCounters.set(match.timeslot, courtNum);

        return {
          team1_id: match.team1Id,
          team2_id: match.team2Id,
          date: dateWithTime.toISOString(),
          location: `Court ${courtNum}`,
          iscompleted: false,
          round_number: 0,
          team1_score: 0,
          team2_score: 0,
          team1_game_wins: 0,
          team2_game_wins: 0,
          season_id: activeSeasonId || null,
          metadata: {
            timeslot: match.timeslot,
            blockType: match.blockType,
            autoGenerated: true,
            generatedAt: new Date().toISOString(),
            dualMatchMode,
          },
        };
      });

      scheduleLog('Saving auto-generated matches to Supabase:', matchesToInsert);

      // Insert matches
      const data = await saveAutoScheduleMatches(matchesToInsert);

      scheduleLog('Successfully saved matches:', data);

      toast({
        title: 'Success',
        description: `Saved ${matches.length} matches to the database`,
      });

      // Clear persisted state after successful save
      clearAutoScheduleState();

      // Invalidate queries to refresh data
      queryClient.invalidateQueries({ queryKey: ['matches'] });
      queryClient.invalidateQueries({ queryKey: ['upcoming-matches'] });
      queryClient.invalidateQueries({ queryKey: ['schedule'] });

      return true;
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to save matches to database';
      errorLog('Error saving matches:', error);
      toast({
        title: 'Error Saving Matches',
        description: message,
        variant: 'destructive',
      });
      return false;
    } finally {
      setIsSaving(false);
    }
  };

  return {
    saveMatches,
    isSaving,
  };
}
