import { useState } from 'react';
import { useToast } from '@/hooks/use-toast';
import { useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { AutoScheduleMatch } from '@/types/autoSchedule';
import { createDateWithTime } from '@/components/schedule/form-utils';

export function useAutoScheduleSave() {
  const [isSaving, setIsSaving] = useState(false);
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const saveMatches = async (
    matches: AutoScheduleMatch[],
    selectedDate: Date | null
  ): Promise<boolean> => {
    if (!selectedDate || !matches || matches.length === 0) {
      toast({
        title: "Error",
        description: "No matches to save or date not selected",
        variant: "destructive"
      });
      return false;
    }

    setIsSaving(true);

    try {
      // Get active season
      const { data: activeSeason, error: seasonError } = await supabase
        .from('seasons')
        .select('id')
        .eq('is_active', true)
        .maybeSingle();

      if (seasonError) throw seasonError;

      // Validate matches
      const teamIds = new Set<string>();
      for (const match of matches) {
        if (!match.team1Id || !match.team2Id) {
          throw new Error('Invalid match data: missing team IDs');
        }
        if (teamIds.has(match.team1Id) || teamIds.has(match.team2Id)) {
          throw new Error('Team appears in multiple matches');
        }
        teamIds.add(match.team1Id);
        teamIds.add(match.team2Id);
      }

      // Transform AutoScheduleMatch to database format
      const matchesToInsert = matches.map((match, index) => {
        // Create UTC date with time
        const dateWithTime = createDateWithTime(selectedDate, match.timeslot);

        return {
          team1_id: match.team1Id,
          team2_id: match.team2Id,
          date: dateWithTime.toISOString(),
          location: `Court ${index + 1}`,
          iscompleted: false,
          round_number: 0,
          team1_score: 0,
          team2_score: 0,
          team1_game_wins: 0,
          team2_game_wins: 0,
          season_id: activeSeason?.id || null,
          metadata: {
            timeslot: match.timeslot,
            blockType: match.blockType,
            autoGenerated: true,
            generatedAt: new Date().toISOString()
          }
        };
      });

      console.log('💾 Saving auto-generated matches to Supabase:', matchesToInsert);

      // Insert matches
      const { data, error } = await supabase
        .from('matches')
        .insert(matchesToInsert)
        .select();

      if (error) throw error;

      console.log('✅ Successfully saved matches:', data);

      toast({
        title: "Success",
        description: `Saved ${matches.length} matches to the database`,
      });

      // Invalidate queries to refresh data
      queryClient.invalidateQueries({ queryKey: ['matches'] });
      queryClient.invalidateQueries({ queryKey: ['upcoming-matches'] });
      queryClient.invalidateQueries({ queryKey: ['schedule'] });

      return true;
    } catch (error: any) {
      console.error('❌ Error saving matches:', error);
      toast({
        title: "Error Saving Matches",
        description: error.message || "Failed to save matches to database",
        variant: "destructive"
      });
      return false;
    } finally {
      setIsSaving(false);
    }
  };

  return {
    saveMatches,
    isSaving
  };
}
