import { PostgrestError } from '@supabase/supabase-js';

import { supabase } from '@/integrations/supabase/client';
import { PowerWeightsNotAppliedError } from '@/types/errors';
import { handleDatabaseError } from '@/utils/errorHandler';
import type { PowerScoreWeights } from '@/utils/powerScore/weights';

/** One row of power_score_weight_history, as get_power_score_weights() returns it. */
export interface PowerWeightRow {
  id: number;
  win_weight: number;
  sos_weight: number;
  game_weight: number;
  applied_at: string;
  note: string | null;
}

export interface PowerWeightState {
  /** false while migration 20260820120000 is not applied to the live database */
  controlsApplied: boolean;
  /** The live triple (null only while the controls are missing) */
  current: PowerWeightRow | null;
  /** What admin_revert_power_score_weights() would restore (null when nothing to revert) */
  previous: PowerWeightRow | null;
}

/** What admin_set_power_score_weights() / admin_revert_power_score_weights() report back. */
export interface PowerWeightMutationResult {
  status: 'applied' | 'reasserted' | 'reverted' | 'nothing_to_revert';
  seasonRows: number;
}

/** One row of the shared components views (0-1 scale terms the formula eats). */
export interface PowerScoreComponentRow {
  team_id: string;
  matches_played: number;
  wins: number;
  losses: number;
  game_wins: number;
  game_losses: number;
  weighted_win_pct: number | null;
  sos: number | null;
  weighted_game_win_pct: number | null;
}

/** A components row scoped to one historical season. */
export interface SeasonPowerScoreComponentRow extends PowerScoreComponentRow {
  season_id: string;
}

/** Convert a history row to the shape the formula mirrors take. */
export const toPowerScoreWeights = (row: PowerWeightRow): PowerScoreWeights => ({
  win: row.win_weight,
  sos: row.sos_weight,
  game: row.game_weight,
});

// TODO(types): temporary cast, same precedent as PowerMigrationService. The
// get/admin_* functions below are created by migration 20260820120000, and
// src/integrations/supabase/types.ts is regenerated by Lovable only after
// that migration reaches the live project. Until then the generated Database
// type doesn't know these function names, so calls go through this narrow
// untyped binding. Remove it (and use supabase.rpc directly) once types.ts
// includes the power-weight functions.
type UntypedRpc = (
  fn: string,
  args?: Record<string, unknown>
) => PromiseLike<{ data: unknown; error: PostgrestError | null }>;
const untypedRpc = supabase.rpc.bind(supabase) as unknown as UntypedRpc;

// "Not applied yet" error codes, same set PowerMigrationService keys on:
// PGRST202: PostgREST schema-cache miss for a function
// 42883:    undefined function at the Postgres level
// PGRST205: PostgREST schema-cache miss for a table
// 42P01:    undefined relation
const NOT_APPLIED_CODES = ['PGRST202', '42883', 'PGRST205', '42P01'];

const CONTROLS_MISSING_STATE: PowerWeightState = {
  controlsApplied: false,
  current: null,
  previous: null,
};

const toMutationResult = (data: unknown): PowerWeightMutationResult => {
  const row = (data ?? {}) as { status?: string; season_rows?: number };
  return {
    status: (row.status ?? 'applied') as PowerWeightMutationResult['status'],
    seasonRows: row.season_rows ?? 0,
  };
};

export const PowerWeightSandboxService = {
  /**
   * The live weight triple plus the one a revert would restore. A missing
   * get_power_score_weights() means the sandbox migration hasn't been applied
   * — reported as controlsApplied:false rather than thrown, so the UI can
   * show its friendly "not applied yet" card without an error toast.
   */
  fetchWeightState: async (): Promise<PowerWeightState> => {
    const { data, error } = await untypedRpc('get_power_score_weights');
    if (error) {
      if (NOT_APPLIED_CODES.includes(error.code)) return CONTROLS_MISSING_STATE;
      handleDatabaseError(error, 'Failed to fetch the power score weights');
    }
    const rows = (Array.isArray(data) ? data : []) as PowerWeightRow[];
    if (rows.length === 0) return CONTROLS_MISSING_STATE;
    return {
      controlsApplied: true,
      current: rows[0],
      previous: rows[1] ?? null,
    };
  },

  /**
   * Current-season formula components for every team (0-1 scale). These views
   * predate the sandbox (unification migrations, 20260809*), so a failure
   * here is a real error, not a "not applied yet" state.
   */
  fetchCurrentSeasonComponents: async (): Promise<PowerScoreComponentRow[]> => {
    const { data, error } = await supabase
      .from('v_power_score_components_current')
      .select(
        'team_id, matches_played, wins, losses, game_wins, game_losses, weighted_win_pct, sos, weighted_game_win_pct'
      );

    if (error) handleDatabaseError(error, 'Failed to fetch current season score components');
    return (data ?? []).flatMap((row) =>
      row.team_id === null
        ? []
        : [
            {
              team_id: row.team_id,
              matches_played: row.matches_played ?? 0,
              wins: row.wins ?? 0,
              losses: row.losses ?? 0,
              game_wins: row.game_wins ?? 0,
              game_losses: row.game_losses ?? 0,
              weighted_win_pct: row.weighted_win_pct,
              sos: row.sos,
              weighted_game_win_pct: row.weighted_game_win_pct,
            },
          ]
    );
  },

  /** Per-season formula components for every team and season (0-1 scale). */
  fetchAllSeasonsComponents: async (): Promise<SeasonPowerScoreComponentRow[]> => {
    const { data, error } = await supabase
      .from('v_power_score_components')
      .select(
        'season_id, team_id, matches_played, wins, losses, game_wins, game_losses, weighted_win_pct, sos, weighted_game_win_pct'
      );

    if (error) handleDatabaseError(error, 'Failed to fetch historical score components');
    return (data ?? []).flatMap((row) =>
      row.team_id === null || row.season_id === null
        ? []
        : [
            {
              team_id: row.team_id,
              season_id: row.season_id,
              matches_played: row.matches_played ?? 0,
              wins: row.wins ?? 0,
              losses: row.losses ?? 0,
              game_wins: row.game_wins ?? 0,
              game_losses: row.game_losses ?? 0,
              weighted_win_pct: row.weighted_win_pct,
              sos: row.sos,
              weighted_game_win_pct: row.weighted_game_win_pct,
            },
          ]
    );
  },

  /**
   * Admin-only. Applies a new weight triple and recomputes every stored
   * season (archived included) in one transaction. Throws
   * PowerWeightsNotAppliedError while the sandbox migration is missing
   * (the UI disables Save in that state, so reaching this is unexpected).
   */
  applyWeights: async (
    weights: PowerScoreWeights,
    note?: string
  ): Promise<PowerWeightMutationResult> => {
    const { data, error } = await untypedRpc('admin_set_power_score_weights', {
      p_win: weights.win,
      p_sos: weights.sos,
      p_game: weights.game,
      p_note: note ?? null,
    });
    if (error) {
      if (NOT_APPLIED_CODES.includes(error.code)) throw new PowerWeightsNotAppliedError();
      handleDatabaseError(error, 'Failed to apply the power score weights');
    }
    return toMutationResult(data);
  },

  /** Admin-only. Restores the previous triple and recomputes every stored season. */
  revertWeights: async (): Promise<PowerWeightMutationResult> => {
    const { data, error } = await untypedRpc('admin_revert_power_score_weights');
    if (error) {
      if (NOT_APPLIED_CODES.includes(error.code)) throw new PowerWeightsNotAppliedError();
      handleDatabaseError(error, 'Failed to revert the power score weights');
    }
    return toMutationResult(data);
  },
};
