import { PostgrestError } from '@supabase/supabase-js';

import { supabase } from '@/integrations/supabase/client';
import { PowerMigrationNotAppliedError } from '@/types/errors';
import { handleDatabaseError } from '@/utils/errorHandler';

export type PowerMigrationState =
  /** Both views use the unified formula */
  | 'applied'
  /** Backup exists and the old formula has been restored */
  | 'reverted'
  /** One view unified, one not — an interrupted revert/reapply */
  | 'partial'
  /** The unification migrations (20260809*) have not run on this database */
  | 'not_applied'
  /** The admin-control migration (20260810120000) itself has not run */
  | 'controls_missing';

export interface PowerMigrationStatus {
  status: PowerMigrationState;
  /** When the pre-unification backup was taken (null until it exists) */
  backedUpAt: string | null;
  backupSeasonRows: number;
  backupTeamRows: number;
  liveSeasonRows: number;
}

/** One row of the team_season_stats backup, joined to its season name */
export interface BackupSeasonStatsRow {
  season_id: string;
  team_id: string;
  match_wins: number;
  match_losses: number;
  game_wins: number;
  game_losses: number;
  division_name: string | null;
  playoff_rank: number | null;
  power_score: number | null;
  sos: number | null;
  champion: boolean | null;
  runner_up: boolean;
  recorded_at: string | null;
  backed_up_at: string;
  season_name: string | null;
}

/** One row of the v_team_details power/record backup */
export interface BackupTeamPowerRow {
  team_id: string;
  power_score: number | null;
  wins: number | null;
  losses: number | null;
  game_wins: number | null;
  game_losses: number | null;
  win_percentage: number | null;
  game_win_percentage: number | null;
  backed_up_at: string;
}

// TODO(types): temporary cast. The admin_* functions below are created by
// migration 20260810120000, and src/integrations/supabase/types.ts is
// regenerated by Lovable only after that migration is applied to the live
// project. Until then the generated Database type doesn't know these function
// names, so calls go through this narrow untyped binding. Remove it (and use
// supabase.rpc directly) once types.ts includes the admin_power_* functions.
type UntypedRpc = (fn: string) => PromiseLike<{ data: unknown; error: PostgrestError | null }>;
const untypedRpc = supabase.rpc.bind(supabase) as unknown as UntypedRpc;

// "Not applied yet" error codes, extending the live-scoring precedent:
// PGRST202: PostgREST schema-cache miss for a function (what the API returns
//           before the controls migration is applied)
// 42883:    undefined function at the Postgres level
// PGRST205: PostgREST schema-cache miss for a table
// 42P01:    undefined relation (the backup readers raise this through the RPC
//           when the unification migrations haven't created the backup tables)
const NOT_APPLIED_CODES = ['PGRST202', '42883', 'PGRST205', '42P01'];

interface RawStatusRow {
  status: PowerMigrationState;
  backed_up_at: string | null;
  backup_season_rows: number;
  backup_team_rows: number;
  live_season_rows: number;
}

const CONTROLS_MISSING_STATUS: PowerMigrationStatus = {
  status: 'controls_missing',
  backedUpAt: null,
  backupSeasonRows: 0,
  backupTeamRows: 0,
  liveSeasonRows: 0,
};

export const PowerMigrationService = {
  /**
   * Admin-only. Where the power-score unification stands on the live database.
   * A missing status function means the controls migration itself hasn't been
   * applied — reported as a state rather than thrown, so the UI can show its
   * friendly "not applied yet" card without an error toast.
   */
  fetchStatus: async (): Promise<PowerMigrationStatus> => {
    const { data, error } = await untypedRpc('admin_power_unification_status');
    if (error) {
      if (NOT_APPLIED_CODES.includes(error.code)) return CONTROLS_MISSING_STATUS;
      handleDatabaseError(error, 'Failed to fetch power score migration status');
    }
    const row = (Array.isArray(data) ? data[0] : data) as RawStatusRow | undefined;
    if (!row) return CONTROLS_MISSING_STATUS;
    return {
      status: row.status,
      backedUpAt: row.backed_up_at,
      backupSeasonRows: row.backup_season_rows ?? 0,
      backupTeamRows: row.backup_team_rows ?? 0,
      liveSeasonRows: row.live_season_rows ?? 0,
    };
  },

  /**
   * Admin-only. The pre-unification team_season_stats backup (with season
   * names). Throws PowerMigrationNotAppliedError while the unification
   * migrations haven't created the backup tables.
   */
  fetchBackupSeasonStats: async (): Promise<BackupSeasonStatsRow[]> => {
    const { data, error } = await untypedRpc('admin_get_pre_unification_season_stats');
    if (error) {
      if (NOT_APPLIED_CODES.includes(error.code)) throw new PowerMigrationNotAppliedError();
      handleDatabaseError(error, 'Failed to fetch the pre-migration season stats backup');
    }
    return (data ?? []) as BackupSeasonStatsRow[];
  },

  /**
   * Admin-only. The pre-unification v_team_details power/record backup.
   * Throws PowerMigrationNotAppliedError while the backup tables don't exist.
   */
  fetchBackupTeamPower: async (): Promise<BackupTeamPowerRow[]> => {
    const { data, error } = await untypedRpc('admin_get_pre_unification_team_power');
    if (error) {
      if (NOT_APPLIED_CODES.includes(error.code)) throw new PowerMigrationNotAppliedError();
      handleDatabaseError(error, 'Failed to fetch the pre-migration team power backup');
    }
    return (data ?? []) as BackupTeamPowerRow[];
  },

  /**
   * Admin-only. Restores the old power-score formula and recomputes every
   * season's stats under it (games played since the backup are kept).
   * Returns 'reverted' or 'already_reverted'.
   */
  revert: async (): Promise<string> => {
    const { data, error } = await untypedRpc('admin_revert_power_score_unification');
    if (error) handleDatabaseError(error, 'Failed to revert the power score migration');
    return typeof data === 'string' ? data : '';
  },

  /**
   * Admin-only. Restores the unified formula and recomputes every season's
   * stats under it. Returns 'applied' or 'already_applied'.
   */
  reapply: async (): Promise<string> => {
    const { data, error } = await untypedRpc('admin_reapply_power_score_unification');
    if (error) handleDatabaseError(error, 'Failed to re-apply the power score migration');
    return typeof data === 'string' ? data : '';
  },
};
