-- NEUTRALIZED — this migration can never have applied cleanly.
-- (Lovable's runner tolerates failed statements, so fragments may have
-- taken effect on the live project; everything load-bearing here is
-- superseded by the working rewrite named below.)
--
-- 20251021165251 (7 hours earlier) already created the same
-- "Admins can insert/update/delete playoff matches" policies. Re-creating
-- them without dropping first errors with "already exists", so this
-- near-duplicate regeneration always aborted (same pattern as
-- 20251021234201, neutralized for the same reason).
-- Original text kept below, commented out, for history.

-- -- Add RLS policies for playoff_matches table to allow admins to manage playoff matches
--
-- -- Add INSERT policy for admins to create playoff matches
-- CREATE POLICY "Admins can insert playoff matches"
-- ON public.playoff_matches
-- FOR INSERT
-- TO authenticated
-- WITH CHECK (current_user_is_admin());
--
-- -- Add UPDATE policy for admins to update match results
-- CREATE POLICY "Admins can update playoff matches"
-- ON public.playoff_matches
-- FOR UPDATE
-- TO authenticated
-- USING (current_user_is_admin())
-- WITH CHECK (current_user_is_admin());
--
-- -- Add DELETE policy for admins to delete playoff matches
-- CREATE POLICY "Admins can delete playoff matches"
-- ON public.playoff_matches
-- FOR DELETE
-- TO authenticated
-- USING (current_user_is_admin());
