
-- Add covering indexes for unindexed foreign keys
CREATE INDEX IF NOT EXISTS idx_admin_notifications_created_by ON public.admin_notifications(created_by);
CREATE INDEX IF NOT EXISTS idx_brackets_division_id ON public.brackets(division_id);
CREATE INDEX IF NOT EXISTS idx_brackets_wb_champion_id ON public.brackets(wb_champion_id);
CREATE INDEX IF NOT EXISTS idx_debug_match_updates_user_id ON public.debug_match_updates(user_id);
CREATE INDEX IF NOT EXISTS idx_game_players_player_team ON public.game_players(player_id, team_id);
CREATE INDEX IF NOT EXISTS idx_game_players_team_id ON public.game_players(team_id);
CREATE INDEX IF NOT EXISTS idx_games_winner_team_id ON public.games(winner_team_id);
CREATE INDEX IF NOT EXISTS idx_match_rounds_entered_by_user_id ON public.match_rounds(entered_by_user_id);
CREATE INDEX IF NOT EXISTS idx_match_rounds_game_match ON public.match_rounds(game_id, match_id);
CREATE INDEX IF NOT EXISTS idx_messages_team_id ON public.messages(team_id);
CREATE INDEX IF NOT EXISTS idx_messages_user_id ON public.messages(user_id);
CREATE INDEX IF NOT EXISTS idx_participant_team_id ON public.participant(team_id);
CREATE INDEX IF NOT EXISTS idx_team_players_profile_id ON public.team_players(profile_id);
CREATE INDEX IF NOT EXISTS idx_team_requests_team_id ON public.team_requests(team_id);

-- Drop unused indexes
DROP INDEX IF EXISTS public.idx_season_team_participation_submitted_by;
DROP INDEX IF EXISTS public.idx_season_team_participation_team_id;
DROP INDEX IF EXISTS public.idx_score_submissions_match_id;
DROP INDEX IF EXISTS public.idx_score_submissions_reviewed_by;
DROP INDEX IF EXISTS public.score_submissions_user_id_idx;
DROP INDEX IF EXISTS public.score_submissions_team_id_idx;
DROP INDEX IF EXISTS public.idx_team_analysis_created_by;
DROP INDEX IF EXISTS public.idx_team_analysis_updated_by;
DROP INDEX IF EXISTS public.idx_seasons_is_active;
DROP INDEX IF EXISTS public.idx_seasons_champion_team_id;
DROP INDEX IF EXISTS public.idx_seasons_runner_up_team_id;
DROP INDEX IF EXISTS public.idx_seasons_third_place_team_id;
DROP INDEX IF EXISTS public.idx_seasons_playoffs_active;
DROP INDEX IF EXISTS public.idx_blind_draw_signups_event_date;
DROP INDEX IF EXISTS public.idx_brackets_season_id;
DROP INDEX IF EXISTS public.match_comments_match_id_idx;
DROP INDEX IF EXISTS public.idx_match_game_match;
DROP INDEX IF EXISTS public.matches_archive_loser_id_idx;
DROP INDEX IF EXISTS public.idx_matches_pending_scores;
DROP INDEX IF EXISTS public.idx_match_rounds_thrower1;
DROP INDEX IF EXISTS public.idx_match_rounds_thrower2;
DROP INDEX IF EXISTS public.idx_game_players_player_id;
DROP INDEX IF EXISTS public.idx_messages_created_at;
DROP INDEX IF EXISTS public.idx_playoff_team_records_bracket_id;
DROP INDEX IF EXISTS public.idx_snapshots_season_week;
DROP INDEX IF EXISTS public.idx_power_score_snapshots_division_id;
DROP INDEX IF EXISTS public.idx_playoff_matches_loser_id;
DROP INDEX IF EXISTS public.idx_playoff_games_match_id;
DROP INDEX IF EXISTS public.idx_playoff_games_winner_id;
DROP INDEX IF EXISTS public.idx_team_stats_team_id;
DROP INDEX IF EXISTS public.idx_team_timeslots_back_to_back;
DROP INDEX IF EXISTS public.idx_team_timeslots_team_id;
DROP INDEX IF EXISTS public.idx_team_memberships_team_user;
DROP INDEX IF EXISTS public.idx_team_memberships_approved_by;
DROP INDEX IF EXISTS public.idx_team_requests_status;
DROP INDEX IF EXISTS public.idx_team_requests_season_id;
DROP INDEX IF EXISTS public.idx_team_season_opt_out_season_id;
DROP INDEX IF EXISTS public.idx_teams_spotify_url;
DROP INDEX IF EXISTS public.admin_notifications_created_at_idx;
DROP INDEX IF EXISTS public.idx_contact_requests_status_created;
DROP INDEX IF EXISTS public.idx_games_match_id;
